name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  codeStyle:
    
    runs-on: ubuntu-latest
    
    name: Dart codestyle checker
    
    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
        
      - name: Starting linting
        run: |
          cd flapp
          flutter pub get
          flutter analyze
  
  tests:
    needs: [codeStyle]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.9.1+hotfix.6'
    - run: |
        cd flapp
        flutter pub get
        flutter test
  
  docker:
    
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     
     - name: Docker version
       run: docker -v
     
     - name: Docker build
       run: |
         docker build -t ${{ secrets.DOCKER_LOGIN }}/flapp:ver_$GITHUB_RUN_NUMBER .
         docker images
         
     - name: Upload to docker hub
       run: |
         docker login --username=${{ secrets.DOCKER_LOGIN }} --password=${{ secrets.DOCKER_PASSWORD }}
         docker push ${{ secrets.USERNAME }}/$PROJECT_NAME:ver_$GITHUB_RUN_NUMBER     
    
   
  
